create database learn;
use learn;
drop database learn;
create database learn;
use learn;
create table course(id int(11) primary key, name  varchar(100) not null, city varchar(50));
show tables;
desc course;

show tables;
drop tables course;
create table course(id int(11) primary key, name varchar(100) not null, city varchar(50));
desc course;
alter table course rename to skill;
desc skill;
truncate table skill;
desc skill;
insert into skill(id, name, city) values(108, 'harpalsinh', 'vadodara');
insert into skill(id, city, name) values(107, 'vapi', 'ashish');
show tables;
desc skill;
select * from skill;
insert into skill values(106, 'ashwini', 'mehsana');
select * from skill;
alter table skill add  country varchar(50);
select * from skill;
update skill set country='india' where id=108;
select * from skill;
update skill set country='brazil' where id=106;
select * from skill;
update skill set country='mexico' where id=107;
select * from skill;
update skill set country='india' where id=107;
select * from skill;
update skill set city='pune' where id=108;
select * from skill;
update skill set city='delhi', country='australia' where id=107;
select * from skill;
delete from skill where id=106;
select * from skill;
insert into skill values(113, 'harry', 'sillycon velly','usa');
select * from skill;
select * from skill where country='nepal';
select name,city,country from skill where city='pune';
select name,country from skill;
select name,city from skill where id=110;
select name as "USERNAME", city as "CITYNAME" from skill;
select country from skill;
insert into skill values(116, 'waz','banglore','india');
select country from skill;
select distinct(country) from skill;
select * from skill;
select * from skill where country='india' and city='pune';
select * from skill where country='india' or city = 'banglore';
select * from skill where id>=110 and id<=115;
select * from skill where id between 109 and 114;
select * from skill where id>108 and id<112;
select * from skill where id=107 or id=109 or id=115;
select * from skill where id in(107,112,115);
select * from skill;
select * from skill limit 5;
select * from skill limit 1 offset 2;
select * from skill order by id desc;
select * from skill order by name desc;
select * from skill;
select * from skill order by id desc limit 2;
select * from skill where name like 'a%';
select * from skill  where city like '_u%';
select * from skill where city like '%n_';
select sum(id) as "Total Salary" from skill;
select avg(id) as "Average salary" from skill;
select count(id) from skill;
select min(id) from skill;
select name from skill where id=(select min(id) from skill);
select name from skill where id=(select max(id) from skill);
alter table skill rename customer;
select * from customer;
create table laptops(lid int primary key, lmodel varchar(50), customerId int, foreign key(customerId) references customer(id));
select * from laptops;
insert into laptops values(1, 'dell', 107);
insert into laptops values(2, 'apple macbookpro', 108);
select * from laptops;
select customer.name, customer.city, laptops.lmodel from customer, laptops where customer.id=laptops.customerId and customer.name='harpalsinh';
select customer.name, laptops.lmodel from customer inner join laptops on customer.id=laptops.customerId;